### ISSUE TITLE
Problems running UCEasy after installing with pip3

### ISSUE THREAD

**Issue by BirdmanRidesAgain** [uceasy/uceasy#9]
Hi!

I'm a previous user of Phyluce who was interested in running UCEasy in an OSX environment to streamline my current UCE workflow. I have a working Phyluce distribution (1.6) installed via conda, but haven't had occasion to use pip (or pip3) before. After running pip3 install uceasy, I received a message stating that the package has successfully installed, and is located in 
./Library/Python/3.9/lib/python/site-packages. However, the actual 'uceasy trim' command doesn't appear to be in my path (included below) or anywhere accessible. 
Additionally, while my base Python satisfies the >3.7 requirement for UCEasy (python3.10.9), the python running in my Phyluce conda environment does not (python3.6.15).

I hate to ask what might be dumb questions, but:
1. Do you know what, exactly, I would add to my path statement (included below) to allow the uceasy commands to be recognized? 
2. How does UCEasy synergize with an activate coda environment where the Python version doesn't satisfy the UCEasy requirements? Do I just need to upgrade Python within conda?

Thanks in advance; hope this isn't too trivial of an issue.

### PATH STATEMENT ###
/Users/keilercollier/mambaforge/envs/phyluce/bin:/Users/keilercollier/mambaforge/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin

**Comment by caioraposo** [comment]
Hi,

For my linux machine pip puts the executable at `$HOME/.local/bin/uceasy` but I don't know where it would be on OSX. But it might tell you where it is located if you try to uninstall uceasy:

```
$ pip uninstall uceasy
Found existing installation: uceasy 0.3.1
Uninstalling uceasy-0.3.1:
  Would remove:
    /home/caio/.local/bin/uceasy
    /home/caio/.local/lib/python3.11/site-packages/uceasy-0.3.1.dist-info/*
    /home/caio/.local/lib/python3.11/site-packages/uceasy/*
Proceed (Y/n)? n
```

> How does UCEasy synergize with an activate coda environment where the Python version doesn't satisfy the UCEasy requirements? Do I just need to upgrade Python within conda?

As for the python version, I thought of using 3.6 in order to be compatible with phyluce but decided it was probably not worth it (I'm probably using some feature from python3.7). But in reality your uceasy installation shouldn't reside in the conda environment, so make sure you're using the correct pip executable (probably in /bin/pip).

I think it would be better if uceasy could be installed with conda and just pull phyluce as a dependecy but we'll most likely have to downgrade the python version.

**Comment by BirdmanRidesAgain** [comment]
Thanks for the response!

I was able to use pip3 uninstall to find the location of uceasy and add it to my path - it works now. And you were correct; the Python 3.7/3.6 issues weren't a problem. I do agree that a conda environment with Phyluce as a dependency would probably be easier, although PHyluce tends to be a little weird when it comes to installation via conda. Either way, you've helped clarify a couple of things, and I appreciate it.

**Comment by caioraposo** [comment]
Glad I was able to help. I'm closing this issue but feel free to reopen it if necessary.
